// AUTO-GENERATED by scripts/build-treatment-content-index.js — do not edit by hand.
import type { TreatmentRichContent } from '@/components/treatments/treatment-rich-sections'

import aboIncompatibleTransplant from './abo-incompatible-transplant.json'
import aclReconstruction from './acl-reconstruction.json'
import acneScarRemoval from './acne-scar-removal.json'
import acupuncture from './acupuncture.json'
import angioplasty from './angioplasty.json'
import botoxInjections from './botox-injections.json'
import brainTumorSurgery from './brain-tumor-surgery.json'
import breastAugmentation from './breast-augmentation.json'
import breastConservingSurgery from './breast-conserving-surgery.json'
import bronchoplasty from './bronchoplasty.json'
import cancerScreening from './cancer-screening.json'
import cardiacScreening from './cardiac-screening.json'
import cardiovascularPhysiologyAssessment from './cardiovascular-physiology-assessment.json'
import cataractSurgery from './cataract-surgery.json'
import chemicalPeel from './chemical-peel.json'
import colonoscopy from './colonoscopy.json'
import congenitalHeartDefectSurgery from './congenital-heart-defect-surgery.json'
import conservativeDentistry from './conservative-dentistry.json'
import corneaTransplant from './cornea-transplant.json'
import cornealTransplant from './corneal-transplant.json'
import coronaryArteryBypassGrafting from './coronary-artery-bypass-grafting.json'
import coronaryBypass from './coronary-bypass.json'
import cuppingTherapy from './cupping-therapy.json'
import cyberknife from './cyberknife.json'
import dentalImplantSurgery from './dental-implant-surgery.json'
import dentalImplants from './dental-implants.json'
import digitalGuidedImplantSurgery from './digital-guided-implant-surgery.json'
import doubleEyelidSurgery from './double-eyelid-surgery.json'
import dualDonorLiverTransplant from './dual-donor-liver-transplant.json'
import eggFreezing from './egg-freezing.json'
import endoscopicSubmucosalDissection from './endoscopic-submucosal-dissection.json'
import endoscopicThyroidectomy from './endoscopic-thyroidectomy.json'
import endoscopy from './endoscopy.json'
import exchangeDonorKidneyTransplant from './exchange-donor-kidney-transplant.json'
import facelift from './facelift.json'
import fertilityConsultation from './fertility-consultation.json'
import fullMouthReconstruction from './full-mouth-reconstruction.json'
import gastricBypass from './gastric-bypass.json'
import gastricSleeve from './gastric-sleeve.json'
import gynecomastiaSurgery from './gynecomastia-surgery.json'
import hairTransplant from './hair-transplant.json'
import healthScreening from './health-screening.json'
import heartTransplant from './heart-transplant.json'
import hemorrhoidSurgery from './hemorrhoid-surgery.json'
import herbalMedicine from './herbal-medicine.json'
import hipReplacement from './hip-replacement.json'
import hysterectomy from './hysterectomy.json'
import inVitroMaturation from './in-vitro-maturation.json'
import ivfTreatment from './ivf-treatment.json'
import kidneyStoneRemoval from './kidney-stone-removal.json'
import kneeReplacement from './knee-replacement.json'
import koreanMedicine from './korean-medicine.json'
import laparoscopicColorectalSurgery from './laparoscopic-colorectal-surgery.json'
import laparoscopicGastricCancer from './laparoscopic-gastric-cancer.json'
import lasekEyeSurgery from './lasek-eye-surgery.json'
import laserSkinResurfacing from './laser-skin-resurfacing.json'
import lasikEyeSurgery from './lasik-eye-surgery.json'
import leftMainCoronaryIntervention from './left-main-coronary-intervention.json'
import limbLengthening from './limb-lengthening.json'
import liposuction from './liposuction.json'
import livingDonorKidneyTransplant from './living-donor-kidney-transplant.json'
import livingDonorLiverTransplant from './living-donor-liver-transplant.json'
import lungCancerSurgery from './lung-cancer-surgery.json'
import lungTransplant from './lung-transplant.json'
import microsurgicalTese from './microsurgical-tese.json'
import minimallyInvasiveSpineSurgery from './minimally-invasive-spine-surgery.json'
import neonatalCare from './neonatal-care.json'
import neonatalHeartSurgery from './neonatal-heart-surgery.json'
import openMicrodiscectomy from './open-microdiscectomy.json'
import oralMaxillofacialSurgery from './oral-maxillofacial-surgery.json'
import orthodonticTreatment from './orthodontic-treatment.json'
import ovarianTissueCryopreservation from './ovarian-tissue-cryopreservation.json'
import pacemakerImplantation from './pacemaker-implantation.json'
import pancreasTransplant from './pancreas-transplant.json'
import pediatricSurgery from './pediatric-surgery.json'
import percutaneousCoronaryIntervention from './percutaneous-coronary-intervention.json'
import periodontalTreatment from './periodontal-treatment.json'
import porcelainVeneers from './porcelain-veneers.json'
import preimplantationGeneticTesting from './preimplantation-genetic-testing.json'
import prenatalCare from './prenatal-care.json'
import prostateSurgery from './prostate-surgery.json'
import prosthodonticTreatment from './prosthodontic-treatment.json'
import protonTherapy from './proton-therapy.json'
import pulmonaryTreatment from './pulmonary-treatment.json'
import radialArteryApproachPci from './radial-artery-approach-pci.json'
import radiofrequencyAblationLiver from './radiofrequency-ablation-liver.json'
import rehabilitationTherapy from './rehabilitation-therapy.json'
import rhinoplasty from './rhinoplasty.json'
import roboticReproductiveSurgery from './robotic-reproductive-surgery.json'
import roboticThyroidectomy from './robotic-thyroidectomy.json'
import roboticTransplantSurgery from './robotic-transplant-surgery.json'
import scoliosisCorrectionSurgery from './scoliosis-correction-surgery.json'
import sentinelLymphNodeBiopsy from './sentinel-lymph-node-biopsy.json'
import septoplasty from './septoplasty.json'
import singlePortLaparoscopicSurgery from './single-port-laparoscopic-surgery.json'
import sinusSurgery from './sinus-surgery.json'
import skinWhitening from './skin-whitening.json'
import smallIntestineTransplant from './small-intestine-transplant.json'
import smileEyeSurgery from './smile-eye-surgery.json'
import sphincterSavingProcedure from './sphincter-saving-procedure.json'
import spinalDecompressionSurgery from './spinal-decompression-surgery.json'
import spinalFusion from './spinal-fusion.json'
import stereotacticRadiationTherapy from './stereotactic-radiation-therapy.json'
import taviProcedure from './tavi-procedure.json'
import teethWhitening from './teeth-whitening.json'
import thyroidSurgery from './thyroid-surgery.json'
import timeLapseEmbryoMonitoring from './time-lapse-embryo-monitoring.json'
import tonsillectomy from './tonsillectomy.json'
import transforaminalEndoscopicDiscectomy from './transforaminal-endoscopic-discectomy.json'
import tummyTuck from './tummy-tuck.json'
import ubeSpinalSurgery from './ube-spinal-surgery.json'
import vLineSurgery from './v-line-surgery.json'
import varicoseVeinTreatment from './varicose-vein-treatment.json'

export const treatmentContent: Record<string, TreatmentRichContent> = {
  "abo-incompatible-transplant": aboIncompatibleTransplant as unknown as TreatmentRichContent,
  "acl-reconstruction": aclReconstruction as unknown as TreatmentRichContent,
  "acne-scar-removal": acneScarRemoval as unknown as TreatmentRichContent,
  "acupuncture": acupuncture as unknown as TreatmentRichContent,
  "angioplasty": angioplasty as unknown as TreatmentRichContent,
  "botox-injections": botoxInjections as unknown as TreatmentRichContent,
  "brain-tumor-surgery": brainTumorSurgery as unknown as TreatmentRichContent,
  "breast-augmentation": breastAugmentation as unknown as TreatmentRichContent,
  "breast-conserving-surgery": breastConservingSurgery as unknown as TreatmentRichContent,
  "bronchoplasty": bronchoplasty as unknown as TreatmentRichContent,
  "cancer-screening": cancerScreening as unknown as TreatmentRichContent,
  "cardiac-screening": cardiacScreening as unknown as TreatmentRichContent,
  "cardiovascular-physiology-assessment": cardiovascularPhysiologyAssessment as unknown as TreatmentRichContent,
  "cataract-surgery": cataractSurgery as unknown as TreatmentRichContent,
  "chemical-peel": chemicalPeel as unknown as TreatmentRichContent,
  "colonoscopy": colonoscopy as unknown as TreatmentRichContent,
  "congenital-heart-defect-surgery": congenitalHeartDefectSurgery as unknown as TreatmentRichContent,
  "conservative-dentistry": conservativeDentistry as unknown as TreatmentRichContent,
  "cornea-transplant": corneaTransplant as unknown as TreatmentRichContent,
  "corneal-transplant": cornealTransplant as unknown as TreatmentRichContent,
  "coronary-artery-bypass-grafting": coronaryArteryBypassGrafting as unknown as TreatmentRichContent,
  "coronary-bypass": coronaryBypass as unknown as TreatmentRichContent,
  "cupping-therapy": cuppingTherapy as unknown as TreatmentRichContent,
  "cyberknife": cyberknife as unknown as TreatmentRichContent,
  "dental-implant-surgery": dentalImplantSurgery as unknown as TreatmentRichContent,
  "dental-implants": dentalImplants as unknown as TreatmentRichContent,
  "digital-guided-implant-surgery": digitalGuidedImplantSurgery as unknown as TreatmentRichContent,
  "double-eyelid-surgery": doubleEyelidSurgery as unknown as TreatmentRichContent,
  "dual-donor-liver-transplant": dualDonorLiverTransplant as unknown as TreatmentRichContent,
  "egg-freezing": eggFreezing as unknown as TreatmentRichContent,
  "endoscopic-submucosal-dissection": endoscopicSubmucosalDissection as unknown as TreatmentRichContent,
  "endoscopic-thyroidectomy": endoscopicThyroidectomy as unknown as TreatmentRichContent,
  "endoscopy": endoscopy as unknown as TreatmentRichContent,
  "exchange-donor-kidney-transplant": exchangeDonorKidneyTransplant as unknown as TreatmentRichContent,
  "facelift": facelift as unknown as TreatmentRichContent,
  "fertility-consultation": fertilityConsultation as unknown as TreatmentRichContent,
  "full-mouth-reconstruction": fullMouthReconstruction as unknown as TreatmentRichContent,
  "gastric-bypass": gastricBypass as unknown as TreatmentRichContent,
  "gastric-sleeve": gastricSleeve as unknown as TreatmentRichContent,
  "gynecomastia-surgery": gynecomastiaSurgery as unknown as TreatmentRichContent,
  "hair-transplant": hairTransplant as unknown as TreatmentRichContent,
  "health-screening": healthScreening as unknown as TreatmentRichContent,
  "heart-transplant": heartTransplant as unknown as TreatmentRichContent,
  "hemorrhoid-surgery": hemorrhoidSurgery as unknown as TreatmentRichContent,
  "herbal-medicine": herbalMedicine as unknown as TreatmentRichContent,
  "hip-replacement": hipReplacement as unknown as TreatmentRichContent,
  "hysterectomy": hysterectomy as unknown as TreatmentRichContent,
  "in-vitro-maturation": inVitroMaturation as unknown as TreatmentRichContent,
  "ivf-treatment": ivfTreatment as unknown as TreatmentRichContent,
  "kidney-stone-removal": kidneyStoneRemoval as unknown as TreatmentRichContent,
  "knee-replacement": kneeReplacement as unknown as TreatmentRichContent,
  "korean-medicine": koreanMedicine as unknown as TreatmentRichContent,
  "laparoscopic-colorectal-surgery": laparoscopicColorectalSurgery as unknown as TreatmentRichContent,
  "laparoscopic-gastric-cancer": laparoscopicGastricCancer as unknown as TreatmentRichContent,
  "lasek-eye-surgery": lasekEyeSurgery as unknown as TreatmentRichContent,
  "laser-skin-resurfacing": laserSkinResurfacing as unknown as TreatmentRichContent,
  "lasik-eye-surgery": lasikEyeSurgery as unknown as TreatmentRichContent,
  "left-main-coronary-intervention": leftMainCoronaryIntervention as unknown as TreatmentRichContent,
  "limb-lengthening": limbLengthening as unknown as TreatmentRichContent,
  "liposuction": liposuction as unknown as TreatmentRichContent,
  "living-donor-kidney-transplant": livingDonorKidneyTransplant as unknown as TreatmentRichContent,
  "living-donor-liver-transplant": livingDonorLiverTransplant as unknown as TreatmentRichContent,
  "lung-cancer-surgery": lungCancerSurgery as unknown as TreatmentRichContent,
  "lung-transplant": lungTransplant as unknown as TreatmentRichContent,
  "microsurgical-tese": microsurgicalTese as unknown as TreatmentRichContent,
  "minimally-invasive-spine-surgery": minimallyInvasiveSpineSurgery as unknown as TreatmentRichContent,
  "neonatal-care": neonatalCare as unknown as TreatmentRichContent,
  "neonatal-heart-surgery": neonatalHeartSurgery as unknown as TreatmentRichContent,
  "open-microdiscectomy": openMicrodiscectomy as unknown as TreatmentRichContent,
  "oral-maxillofacial-surgery": oralMaxillofacialSurgery as unknown as TreatmentRichContent,
  "orthodontic-treatment": orthodonticTreatment as unknown as TreatmentRichContent,
  "ovarian-tissue-cryopreservation": ovarianTissueCryopreservation as unknown as TreatmentRichContent,
  "pacemaker-implantation": pacemakerImplantation as unknown as TreatmentRichContent,
  "pancreas-transplant": pancreasTransplant as unknown as TreatmentRichContent,
  "pediatric-surgery": pediatricSurgery as unknown as TreatmentRichContent,
  "percutaneous-coronary-intervention": percutaneousCoronaryIntervention as unknown as TreatmentRichContent,
  "periodontal-treatment": periodontalTreatment as unknown as TreatmentRichContent,
  "porcelain-veneers": porcelainVeneers as unknown as TreatmentRichContent,
  "preimplantation-genetic-testing": preimplantationGeneticTesting as unknown as TreatmentRichContent,
  "prenatal-care": prenatalCare as unknown as TreatmentRichContent,
  "prostate-surgery": prostateSurgery as unknown as TreatmentRichContent,
  "prosthodontic-treatment": prosthodonticTreatment as unknown as TreatmentRichContent,
  "proton-therapy": protonTherapy as unknown as TreatmentRichContent,
  "pulmonary-treatment": pulmonaryTreatment as unknown as TreatmentRichContent,
  "radial-artery-approach-pci": radialArteryApproachPci as unknown as TreatmentRichContent,
  "radiofrequency-ablation-liver": radiofrequencyAblationLiver as unknown as TreatmentRichContent,
  "rehabilitation-therapy": rehabilitationTherapy as unknown as TreatmentRichContent,
  "rhinoplasty": rhinoplasty as unknown as TreatmentRichContent,
  "robotic-reproductive-surgery": roboticReproductiveSurgery as unknown as TreatmentRichContent,
  "robotic-thyroidectomy": roboticThyroidectomy as unknown as TreatmentRichContent,
  "robotic-transplant-surgery": roboticTransplantSurgery as unknown as TreatmentRichContent,
  "scoliosis-correction-surgery": scoliosisCorrectionSurgery as unknown as TreatmentRichContent,
  "sentinel-lymph-node-biopsy": sentinelLymphNodeBiopsy as unknown as TreatmentRichContent,
  "septoplasty": septoplasty as unknown as TreatmentRichContent,
  "single-port-laparoscopic-surgery": singlePortLaparoscopicSurgery as unknown as TreatmentRichContent,
  "sinus-surgery": sinusSurgery as unknown as TreatmentRichContent,
  "skin-whitening": skinWhitening as unknown as TreatmentRichContent,
  "small-intestine-transplant": smallIntestineTransplant as unknown as TreatmentRichContent,
  "smile-eye-surgery": smileEyeSurgery as unknown as TreatmentRichContent,
  "sphincter-saving-procedure": sphincterSavingProcedure as unknown as TreatmentRichContent,
  "spinal-decompression-surgery": spinalDecompressionSurgery as unknown as TreatmentRichContent,
  "spinal-fusion": spinalFusion as unknown as TreatmentRichContent,
  "stereotactic-radiation-therapy": stereotacticRadiationTherapy as unknown as TreatmentRichContent,
  "tavi-procedure": taviProcedure as unknown as TreatmentRichContent,
  "teeth-whitening": teethWhitening as unknown as TreatmentRichContent,
  "thyroid-surgery": thyroidSurgery as unknown as TreatmentRichContent,
  "time-lapse-embryo-monitoring": timeLapseEmbryoMonitoring as unknown as TreatmentRichContent,
  "tonsillectomy": tonsillectomy as unknown as TreatmentRichContent,
  "transforaminal-endoscopic-discectomy": transforaminalEndoscopicDiscectomy as unknown as TreatmentRichContent,
  "tummy-tuck": tummyTuck as unknown as TreatmentRichContent,
  "ube-spinal-surgery": ubeSpinalSurgery as unknown as TreatmentRichContent,
  "v-line-surgery": vLineSurgery as unknown as TreatmentRichContent,
  "varicose-vein-treatment": varicoseVeinTreatment as unknown as TreatmentRichContent,
}
