// AUTO-GENERATED by scripts/build-pseo-guides-index.js — do not edit by hand.
import type { ProcedureGuide } from '@/lib/data/pseo-content'

import breastAugmentation from './breast-augmentation.json'
import dentalImplantSurgery from './dental-implant-surgery.json'
import dentalImplants from './dental-implants.json'
import doubleEyelidSurgery from './double-eyelid-surgery.json'
import eggFreezing from './egg-freezing.json'
import facelift from './facelift.json'
import hairTransplant from './hair-transplant.json'
import healthScreening from './health-screening.json'
import ivfTreatment from './ivf-treatment.json'
import kneeReplacement from './knee-replacement.json'
import lasikEyeSurgery from './lasik-eye-surgery.json'
import liposuction from './liposuction.json'
import rhinoplasty from './rhinoplasty.json'
import tummyTuck from './tummy-tuck.json'
import vLineSurgery from './v-line-surgery.json'

export const pseoGuides: Record<string, ProcedureGuide> = {
  "breast-augmentation": breastAugmentation as unknown as ProcedureGuide,
  "dental-implant-surgery": dentalImplantSurgery as unknown as ProcedureGuide,
  "dental-implants": dentalImplants as unknown as ProcedureGuide,
  "double-eyelid-surgery": doubleEyelidSurgery as unknown as ProcedureGuide,
  "egg-freezing": eggFreezing as unknown as ProcedureGuide,
  "facelift": facelift as unknown as ProcedureGuide,
  "hair-transplant": hairTransplant as unknown as ProcedureGuide,
  "health-screening": healthScreening as unknown as ProcedureGuide,
  "ivf-treatment": ivfTreatment as unknown as ProcedureGuide,
  "knee-replacement": kneeReplacement as unknown as ProcedureGuide,
  "lasik-eye-surgery": lasikEyeSurgery as unknown as ProcedureGuide,
  "liposuction": liposuction as unknown as ProcedureGuide,
  "rhinoplasty": rhinoplasty as unknown as ProcedureGuide,
  "tummy-tuck": tummyTuck as unknown as ProcedureGuide,
  "v-line-surgery": vLineSurgery as unknown as ProcedureGuide,
}
