// AUTO-GENERATED by scripts/build-pseo-guides-index.js — do not edit by hand.
import type { ProcedureGuide } from '@/lib/data/pseo-content'

import aclReconstruction from './acl-reconstruction.json'
import acneScarRemoval from './acne-scar-removal.json'
import acupuncture from './acupuncture.json'
import angioplasty from './angioplasty.json'
import botoxInjections from './botox-injections.json'
import brainTumorSurgery from './brain-tumor-surgery.json'
import breastAugmentation from './breast-augmentation.json'
import cancerScreening from './cancer-screening.json'
import cardiacScreening from './cardiac-screening.json'
import dentalImplantSurgery from './dental-implant-surgery.json'
import dentalImplants from './dental-implants.json'
import doubleEyelidSurgery from './double-eyelid-surgery.json'
import eggFreezing from './egg-freezing.json'
import facelift from './facelift.json'
import hairTransplant from './hair-transplant.json'
import healthScreening from './health-screening.json'
import ivfTreatment from './ivf-treatment.json'
import kneeReplacement from './knee-replacement.json'
import lasikEyeSurgery from './lasik-eye-surgery.json'
import liposuction from './liposuction.json'
import rhinoplasty from './rhinoplasty.json'
import tummyTuck from './tummy-tuck.json'
import vLineSurgery from './v-line-surgery.json'

export const pseoGuides: Record<string, ProcedureGuide> = {
  "acl-reconstruction": aclReconstruction as unknown as ProcedureGuide,
  "acne-scar-removal": acneScarRemoval as unknown as ProcedureGuide,
  "acupuncture": acupuncture as unknown as ProcedureGuide,
  "angioplasty": angioplasty as unknown as ProcedureGuide,
  "botox-injections": botoxInjections as unknown as ProcedureGuide,
  "brain-tumor-surgery": brainTumorSurgery as unknown as ProcedureGuide,
  "breast-augmentation": breastAugmentation as unknown as ProcedureGuide,
  "cancer-screening": cancerScreening as unknown as ProcedureGuide,
  "cardiac-screening": cardiacScreening as unknown as ProcedureGuide,
  "dental-implant-surgery": dentalImplantSurgery as unknown as ProcedureGuide,
  "dental-implants": dentalImplants as unknown as ProcedureGuide,
  "double-eyelid-surgery": doubleEyelidSurgery as unknown as ProcedureGuide,
  "egg-freezing": eggFreezing as unknown as ProcedureGuide,
  "facelift": facelift as unknown as ProcedureGuide,
  "hair-transplant": hairTransplant as unknown as ProcedureGuide,
  "health-screening": healthScreening as unknown as ProcedureGuide,
  "ivf-treatment": ivfTreatment as unknown as ProcedureGuide,
  "knee-replacement": kneeReplacement as unknown as ProcedureGuide,
  "lasik-eye-surgery": lasikEyeSurgery as unknown as ProcedureGuide,
  "liposuction": liposuction as unknown as ProcedureGuide,
  "rhinoplasty": rhinoplasty as unknown as ProcedureGuide,
  "tummy-tuck": tummyTuck as unknown as ProcedureGuide,
  "v-line-surgery": vLineSurgery as unknown as ProcedureGuide,
}
