// AUTO-GENERATED by scripts/build-pseo-guides-index.js — do not edit by hand.
import type { ProcedureGuide } from '@/lib/data/pseo-content'

import aclReconstruction from './acl-reconstruction.json'
import acneScarRemoval from './acne-scar-removal.json'
import acupuncture from './acupuncture.json'
import angioplasty from './angioplasty.json'
import botoxInjections from './botox-injections.json'
import brainTumorSurgery from './brain-tumor-surgery.json'
import breastAugmentation from './breast-augmentation.json'
import cancerScreening from './cancer-screening.json'
import cardiacScreening from './cardiac-screening.json'
import cataractSurgery from './cataract-surgery.json'
import chemicalPeel from './chemical-peel.json'
import colonoscopy from './colonoscopy.json'
import cornealTransplant from './corneal-transplant.json'
import coronaryBypass from './coronary-bypass.json'
import cuppingTherapy from './cupping-therapy.json'
import dentalImplantSurgery from './dental-implant-surgery.json'
import dentalImplants from './dental-implants.json'
import doubleEyelidSurgery from './double-eyelid-surgery.json'
import eggFreezing from './egg-freezing.json'
import endoscopy from './endoscopy.json'
import facelift from './facelift.json'
import fertilityConsultation from './fertility-consultation.json'
import gastricBypass from './gastric-bypass.json'
import gastricSleeve from './gastric-sleeve.json'
import gynecomastiaSurgery from './gynecomastia-surgery.json'
import hairTransplant from './hair-transplant.json'
import healthScreening from './health-screening.json'
import hemorrhoidSurgery from './hemorrhoid-surgery.json'
import herbalMedicine from './herbal-medicine.json'
import hipReplacement from './hip-replacement.json'
import hysterectomy from './hysterectomy.json'
import ivfTreatment from './ivf-treatment.json'
import kidneyStoneRemoval from './kidney-stone-removal.json'
import kneeReplacement from './knee-replacement.json'
import koreanMedicine from './korean-medicine.json'
import lasekEyeSurgery from './lasek-eye-surgery.json'
import laserSkinResurfacing from './laser-skin-resurfacing.json'
import lasikEyeSurgery from './lasik-eye-surgery.json'
import limbLengthening from './limb-lengthening.json'
import liposuction from './liposuction.json'
import lungCancerSurgery from './lung-cancer-surgery.json'
import neonatalCare from './neonatal-care.json'
import pacemakerImplantation from './pacemaker-implantation.json'
import pediatricSurgery from './pediatric-surgery.json'
import rhinoplasty from './rhinoplasty.json'
import tummyTuck from './tummy-tuck.json'
import vLineSurgery from './v-line-surgery.json'

export const pseoGuides: Record<string, ProcedureGuide> = {
  "acl-reconstruction": aclReconstruction as unknown as ProcedureGuide,
  "acne-scar-removal": acneScarRemoval as unknown as ProcedureGuide,
  "acupuncture": acupuncture as unknown as ProcedureGuide,
  "angioplasty": angioplasty as unknown as ProcedureGuide,
  "botox-injections": botoxInjections as unknown as ProcedureGuide,
  "brain-tumor-surgery": brainTumorSurgery as unknown as ProcedureGuide,
  "breast-augmentation": breastAugmentation as unknown as ProcedureGuide,
  "cancer-screening": cancerScreening as unknown as ProcedureGuide,
  "cardiac-screening": cardiacScreening as unknown as ProcedureGuide,
  "cataract-surgery": cataractSurgery as unknown as ProcedureGuide,
  "chemical-peel": chemicalPeel as unknown as ProcedureGuide,
  "colonoscopy": colonoscopy as unknown as ProcedureGuide,
  "corneal-transplant": cornealTransplant as unknown as ProcedureGuide,
  "coronary-bypass": coronaryBypass as unknown as ProcedureGuide,
  "cupping-therapy": cuppingTherapy as unknown as ProcedureGuide,
  "dental-implant-surgery": dentalImplantSurgery as unknown as ProcedureGuide,
  "dental-implants": dentalImplants as unknown as ProcedureGuide,
  "double-eyelid-surgery": doubleEyelidSurgery as unknown as ProcedureGuide,
  "egg-freezing": eggFreezing as unknown as ProcedureGuide,
  "endoscopy": endoscopy as unknown as ProcedureGuide,
  "facelift": facelift as unknown as ProcedureGuide,
  "fertility-consultation": fertilityConsultation as unknown as ProcedureGuide,
  "gastric-bypass": gastricBypass as unknown as ProcedureGuide,
  "gastric-sleeve": gastricSleeve as unknown as ProcedureGuide,
  "gynecomastia-surgery": gynecomastiaSurgery as unknown as ProcedureGuide,
  "hair-transplant": hairTransplant as unknown as ProcedureGuide,
  "health-screening": healthScreening as unknown as ProcedureGuide,
  "hemorrhoid-surgery": hemorrhoidSurgery as unknown as ProcedureGuide,
  "herbal-medicine": herbalMedicine as unknown as ProcedureGuide,
  "hip-replacement": hipReplacement as unknown as ProcedureGuide,
  "hysterectomy": hysterectomy as unknown as ProcedureGuide,
  "ivf-treatment": ivfTreatment as unknown as ProcedureGuide,
  "kidney-stone-removal": kidneyStoneRemoval as unknown as ProcedureGuide,
  "knee-replacement": kneeReplacement as unknown as ProcedureGuide,
  "korean-medicine": koreanMedicine as unknown as ProcedureGuide,
  "lasek-eye-surgery": lasekEyeSurgery as unknown as ProcedureGuide,
  "laser-skin-resurfacing": laserSkinResurfacing as unknown as ProcedureGuide,
  "lasik-eye-surgery": lasikEyeSurgery as unknown as ProcedureGuide,
  "limb-lengthening": limbLengthening as unknown as ProcedureGuide,
  "liposuction": liposuction as unknown as ProcedureGuide,
  "lung-cancer-surgery": lungCancerSurgery as unknown as ProcedureGuide,
  "neonatal-care": neonatalCare as unknown as ProcedureGuide,
  "pacemaker-implantation": pacemakerImplantation as unknown as ProcedureGuide,
  "pediatric-surgery": pediatricSurgery as unknown as ProcedureGuide,
  "rhinoplasty": rhinoplasty as unknown as ProcedureGuide,
  "tummy-tuck": tummyTuck as unknown as ProcedureGuide,
  "v-line-surgery": vLineSurgery as unknown as ProcedureGuide,
}
