-- ============================================================
-- Deep Tech Migration (2026 Strategy)
-- Run this to upgrade your existing database with Agent capabilities
-- ============================================================

-- 1. Enhanced Hospital capabilities
-- Add columns to connect hospitals with n8n/APIs and store survival rate data
alter table public.clinics 
add column if not exists api_integration_level text default 'NONE', -- 'NONE' | 'WEBHOOK' | 'FULL_API'
add column if not exists survival_rates jsonb, -- e.g. {"ivf": 0.65, "cardiac": 0.98}
add column if not exists booking_webhook_url text;

-- 2. LangGraph Persistence (Checkpoints)
-- This table stores the state of the AI agent workflows (the "Memory")
create table if not exists public.patient_journey_state (
    patient_id uuid primary key references public.patient_intakes(id),
    current_stage text not null, -- 'INTAKE' | 'TRIAGE' | 'MATCHING' | 'QUOTE' | 'BOOKING'
    thread_id text not null, -- LangGraph thread ID
    checkpoint_data jsonb, -- Serialized graph state
    last_updated_at timestamptz not null default now()
);

-- 3. Payment / Quote Transactions
-- This table tracks the financial offers generated by the agents
create table if not exists public.quotes (
    id uuid primary key default uuid_generate_v4(),
    patient_id uuid references public.patient_intakes(id),
    hospital_id uuid references public.clinics(id),
    total_amount numeric,
    currency text default 'USD',
    status text default 'DRAFT', -- 'DRAFT' | 'SENT' | 'PAID' | 'EXPIRED'
    pdf_url text,
    stripe_payment_link text,
    breakdown jsonb, -- {procedure: 5000, hotel: 1200, flight: 800}
    created_at timestamptz not null default now()
);

-- Verification Query (Run this after applying to confirm success)
-- select column_name from information_schema.columns where table_name = 'clinics' and column_name = 'api_integration_level';
